"""empty message

Revision ID: 0ecdf6b348cd
Revises: 84c930eec4c7
Create Date: 2021-01-18 22:11:20.001059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ecdf6b348cd'
down_revision = '84c930eec4c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('project_id', sa.Integer(), nullable=False))
    op.alter_column('items', 'cluster_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('items', 'is_highlight',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('items', 'is_note',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint('items_parent_project_fkey', 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'projects', ['project_id'], ['id'])
    op.drop_column('items', 'parent_project')
    op.alter_column('sources', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sources', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('items', sa.Column('parent_project', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key('items_parent_project_fkey', 'items', 'projects', ['parent_project'], ['id'])
    op.alter_column('items', 'is_note',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('items', 'is_highlight',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('items', 'cluster_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('items', 'project_id')
    # ### end Alembic commands ###
