"""empty message

Revision ID: 2206a614129b
Revises: 0ecdf6b348cd
Create Date: 2021-01-19 22:42:27.741334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2206a614129b'
down_revision = '0ecdf6b348cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'is_highlight')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('is_highlight', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
