"""empty message

Revision ID: 22828d43d921
Revises: a21fcc3b78a1
Create Date: 2021-01-07 16:52:28.755599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22828d43d921'
down_revision = 'a21fcc3b78a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clusters', sa.Column('parent_cluster_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clusters', 'clusters', ['parent_cluster_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clusters', type_='foreignkey')
    op.drop_column('clusters', 'parent_cluster_id')
    # ### end Alembic commands ###
