"""Ensure unique urls within a project

Revision ID: 31d1310f58bc
Revises: 8235ecabbd5b
Create Date: 2020-08-30 00:55:05.021866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31d1310f58bc'
down_revision = '8235ecabbd5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'sources', ['project_id', 'url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sources', type_='unique')
    # ### end Alembic commands ###
