"""empty message

Revision ID: 3f2220080833
Revises: 
Create Date: 2021-01-21 20:04:54.378878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f2220080833'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('x_position', sa.Integer(), nullable=True),
    sa.Column('y_position', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('parent_cluster_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('(NOT(project_id IS NULL AND parent_cluster_id IS NULL)) AND(NOT(project_id IS NOT NULL AND parent_cluster_id IS NOT NULL))'),
    sa.ForeignKeyConstraint(['parent_cluster_id'], ['clusters.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('x_position', sa.Integer(), nullable=True),
    sa.Column('y_position', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'url')
    )
    op.create_table('edges',
    sa.Column('from_id', sa.Integer(), nullable=False),
    sa.Column('to_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['to_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('from_id', 'to_id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('is_note', sa.Boolean(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('x_position', sa.Integer(), nullable=True),
    sa.Column('y_position', sa.Integer(), nullable=True),
    sa.Column('parent_project', sa.Integer(), nullable=True),
    sa.Column('parent_cluster', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_cluster'], ['clusters.id'], ),
    sa.ForeignKeyConstraint(['parent_project'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    op.drop_table('edges')
    op.drop_table('sources')
    op.drop_table('clusters')
    op.drop_table('projects')
    # ### end Alembic commands ###
