"""empty message

Revision ID: 522df93c1016
Revises: 3f2220080833
Create Date: 2021-01-23 16:19:11.249988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522df93c1016'
down_revision = '3f2220080833'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_projects',
    sa.Column('shared_proj', sa.Integer(), nullable=False),
    sa.Column('shared_user', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['shared_proj'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('shared_proj')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_projects')
    # ### end Alembic commands ###
