"""empty message

Revision ID: 5735c92af385
Revises: b0a719dd58fb
Create Date: 2021-01-18 03:59:54.217295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5735c92af385'
down_revision = 'b0a719dd58fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('cluster_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sources', 'clusters', ['cluster_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sources', type_='foreignkey')
    op.drop_column('sources', 'cluster_id')
    # ### end Alembic commands ###
