"""empty message

Revision ID: 58cff5a4cd1b
Revises: 6e50729c990c
Create Date: 2021-01-20 14:49:07.154838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58cff5a4cd1b'
down_revision = '6e50729c990c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('is_included', sa.Boolean(), nullable=True))
    op.drop_column('sources', 'is_including')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('is_including', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('sources', 'is_included')
    # ### end Alembic commands ###
