"""empty message

Revision ID: 6e50729c990c
Revises: 22828d43d921
Create Date: 2021-01-20 13:17:57.193109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e50729c990c'
down_revision = '22828d43d921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('is_note', sa.BOOLEAN(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('x_position', sa.Integer(), nullable=True),
    sa.Column('y_position', sa.Integer(), nullable=True),
    sa.Column('parent_project', sa.Integer(), nullable=False),
    sa.Column('parent_cluster', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_cluster'], ['clusters.id'], ),
    sa.ForeignKeyConstraint(['parent_project'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('clusters', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('sources', sa.Column('access_date', sa.DateTime(), nullable=True))
    op.add_column('sources', sa.Column('author', sa.String(), nullable=True))
    op.add_column('sources', sa.Column('is_including', sa.Boolean(), nullable=True))
    op.add_column('sources', sa.Column('published_date', sa.DateTime(), nullable=True))
    op.add_column('sources', sa.Column('site_name', sa.String(), nullable=True))
    op.alter_column('sources', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('sources_cluster_id_fkey', 'sources', type_='foreignkey')
    op.drop_column('sources', 'highlights')
    op.drop_column('sources', 'y_position')
    op.drop_column('sources', 'notes')
    op.drop_column('sources', 'cluster_id')
    op.drop_column('sources', 'x_position')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('x_position', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sources', sa.Column('cluster_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sources', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('sources', sa.Column('y_position', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sources', sa.Column('highlights', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('sources_cluster_id_fkey', 'sources', 'clusters', ['cluster_id'], ['id'])
    op.alter_column('sources', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('sources', 'site_name')
    op.drop_column('sources', 'published_date')
    op.drop_column('sources', 'is_including')
    op.drop_column('sources', 'author')
    op.drop_column('sources', 'access_date')
    op.alter_column('clusters', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('items')
    # ### end Alembic commands ###
