"""empty message

Revision ID: 84c930eec4c7
Revises: 31d1310f58bc
Create Date: 2021-01-14 23:31:50.956417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84c930eec4c7'
down_revision = '31d1310f58bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('x_position', sa.Integer(), nullable=True),
    sa.Column('y_position', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('parent_cluster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_cluster_id'], ['clusters.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('is_note', sa.BOOLEAN(), nullable=False),
    sa.Column('is_highlight', sa.BOOLEAN(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('x_position', sa.Integer(), nullable=True),
    sa.Column('y_position', sa.Integer(), nullable=True),
    sa.Column('parent_project', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.ForeignKeyConstraint(['parent_project'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('sources', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('sources', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('sources', 'notes')
    op.drop_column('sources', 'highlights')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('highlights', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('sources', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('sources', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('sources', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('items')
    op.drop_table('clusters')
    # ### end Alembic commands ###
