"""updated column title for project name

Revision ID: 913a811168fe
Revises: 13a272c63ab3
Create Date: 2020-08-25 00:25:14.890778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '913a811168fe'
down_revision = '13a272c63ab3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('title', sa.String(), nullable=False))
    op.drop_column('projects', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('projects', 'title')
    # ### end Alembic commands ###
