"""empty message

Revision ID: a1535a33b7d4
Revises: 31d1310f58bc
Create Date: 2021-01-07 13:47:23.458052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1535a33b7d4'
down_revision = '31d1310f58bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('x_position', sa.Integer(), nullable=True),
    sa.Column('y_position', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('sources', sa.Column('cluster_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sources', 'clusters', ['cluster_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sources', type_='foreignkey')
    op.drop_column('sources', 'cluster_id')
    op.drop_table('clusters')
    # ### end Alembic commands ###
