"""empty message

Revision ID: a21fcc3b78a1
Revises: a1535a33b7d4
Create Date: 2021-01-07 14:24:21.150897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a21fcc3b78a1'
down_revision = 'a1535a33b7d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sources', 'cluster_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sources', 'cluster_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
