"""empty message

Revision ID: abc83a63df8d
Revises: c5d5f52381c5
Create Date: 2021-02-17 14:32:47.552539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc83a63df8d'
down_revision = 'c5d5f52381c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edges')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edges',
    sa.Column('from_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('to_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['sources.id'], name='edges_from_id_fkey'),
    sa.ForeignKeyConstraint(['to_id'], ['sources.id'], name='edges_to_id_fkey'),
    sa.PrimaryKeyConstraint('from_id', 'to_id', name='edges_pkey')
    )
    # ### end Alembic commands ###
