"""empty message

Revision ID: c5d5f52381c5
Revises: 9fe8f7a7782a
Create Date: 2021-02-01 21:07:42.624461

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = 'c5d5f52381c5'
down_revision = '9fe8f7a7782a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Use current date as default for both creation_date and recent_access_date (for columns that didn't have it)
    op.add_column('projects', sa.Column('creation_date', sa.DateTime(), nullable=True))
    op.execute("UPDATE projects SET creation_date='" + str(datetime.utcnow()) + "'")
    op.alter_column('projects', 'creation_date', nullable=False)
    op.add_column('projects', sa.Column('description', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('recent_access_date', sa.DateTime(), nullable=True))
    op.execute("UPDATE projects SET recent_access_date='" + str(datetime.utcnow()) + "'")
    op.alter_column('projects', 'recent_access_date', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'recent_access_date')
    op.drop_column('projects', 'description')
    op.drop_column('projects', 'creation_date')
    # ### end Alembic commands ###
