"""fix issue with project relationship

Revision ID: c830cc51abeb
Revises: 913a811168fe
Create Date: 2020-08-25 01:16:28.225395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c830cc51abeb'
down_revision = '913a811168fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('project_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sources', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sources', type_='foreignkey')
    op.drop_column('sources', 'project_id')
    # ### end Alembic commands ###
